name: Release

on: ["push", "pull_request"]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache pnpm
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Cache tauri
        uses: actions/cache@v2
        env:
          cache-name: cache-cargo-tauri
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Cache backend
        uses: Swatinem/rust-cache@v1.2.0
        with:
          working-directory: ./app/src-tauri

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Setup tauri
        run: cargo install tauri-cli --version ^1.0.0-beta

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Build frontend
        run: pnpm i && pnpm build
        working-directory: ./app/src-ui

      - name: Build backend
        run: cargo tauri build
        working-directory: ./app/

      - name: Lint backend
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./app/src-tauri/Cargo.toml

      - name: Prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Prerelease"
          prerelease: true
          title: "Development Build - May be unstable"
          files: ./app/src-tauri/target/release/bundle/**/tic-tac-toe*.*

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./app/src-tauri/target/release/bundle/**/tic-tac-toe*.dmg
            ./app/src-tauri/target/release/bundle/**/tic-tac-toe*.msi
            ./app/src-tauri/target/release/bundle/**/tic-tac-toe*.dmgas
